### ISSUE TITLE
Invalid ava binary location error

### ISSUE THREAD

**Issue by ozgurrgul** [ava-labs/avash#109]
Hello, I am trying to run ./avash but I got the following error:

``` js
Invalid ava binary location: /home/myuser/go/src/github.com/ava-labs/avalanchego/build/avalanchego
Make sure your $GOPATH is set or provide a configuration file with a valid `avalancheLocation` value. See README.md for more details.
```

How can I provide a `avalancheLocation`? Currently it is installed at:

``` js
/home/myuser/avalanche-node/avalanchego
```

**Comment by tbrunain** [comment]
Hello , I just had a similar issue and you can start avash with this flag : `./avash --config=example.avash.yaml` . in that example.avash.yaml you can set the path behind `avalancheLocation to `/home/myuser/avalanche-node/avalanchego` 

(Just be aware that there is a mistake in that file right now, I have open a pr for it here : https://github.com/ava-labs/avash/pull/110

**Comment by ozgurrgul** [comment]
It seems to work, thanks!
