### ISSUE TITLE
avalanchego dep still at 0.8.0

### ISSUE THREAD

**Issue by tbrunain** [ava-labs/avash#111]
I noticed that the version of avalanchego referenced in the go.mod is still 0.8.0 , is there a reason to that ? 

https://github.com/ava-labs/avash/blob/9f813fb5d8acf3c3dc528dd00dd25b9852a0afa1/go.mod#L7

**Comment by cgcardona** [comment]
This has been fixed in [avash v1.1.0](https://github.com/ava-labs/avash/releases/tag/v1.1.0).
