### ISSUE TITLE
formatting.CB58 is not a type

### ISSUE THREAD

**Issue by visopsys** [ava-labs/avash#116]
I got this error while compiling the source code 
```
formatting.CB58 is not a type
```

What version of avalanchgo should I use with avash on master?

**Comment by cgcardona** [comment]
You should be using the latest and greatest avalanchego—[v1.3.2](https://github.com/ava-labs/avalanchego/releases/tag/v1.3.2). This has been fixed in [avash v1.1.0](https://github.com/ava-labs/avash/releases/tag/v1.1.0).
