### ISSUE TITLE
avash installation issue and a work around

### ISSUE THREAD

**Issue by arikan** [ava-labs/avash#35]
Hi there, I tried the avash installation and `go get github.com/ava-labs/avash` throwed the following error:
```
package go.uber.org/multierr: unrecognized import path "go.uber.org/multierr" (https fetch: Get https://go.uber.org/multierr?go-get=1: net/http: TLS handshake timeout)
```

This might be related to paths but not sure exactly, here is my environment variables for Go on a mac os 10.15.2. 
```
export GOPATH="$HOME/go"
export PATH="$GOPATH/bin:$PATH"
```

However, here is a work around in case someone come across this issue:
```
mkdir -p $GOPATH/src/go.uber.org
cd $GOPATH/src/go.uber.org
git clone git@github.com:uber-go/multierr.git
git clone git@github.com:uber-go/atomic.git
```
Then the avash build works fine.

**Comment by collincusce** [comment]
This was resolved in Discord. Ubers go repo was down for a bit and caused the error, we think. Resolved after a few minutes.
