### ISSUE TITLE
Use the same local certs/keys as Gecko

### ISSUE THREAD

**Issue by danlaine** [ava-labs/avash#36]
When starting nodes, Avash uses certs in `avash/certs/keyX`.
Right now, keys 1 through 5 are the same as `staker1.key`, ..., `staker5.key` in `gecko/keys/local`. 
These keys are currently funded when running a local network but those keys may change in the future.

What do you think of pointing Avash to use the `keys/local` files in the gecko repo instead of replicating them in `avash/certs`?

**Comment by collincusce** [comment]
We actually have to take a look at how certs are done.

So the problem with what you said is that it assumes avash has access to the Gecko folder in the gopath. That's fine when building Avash from scratch, but the build itself should produce everything it needs to execute. Unless I'm missing what you're saying?

**Comment by collincusce** [comment]
I'm pretty sure this was fixed, right @danlaine @cmontag ?

**Comment by danlaine** [comment]
The five node staking script still relies on the staking keys/certs in the `certs` directory

**Comment by collincusce** [comment]
Ah. I see now. Yeah this issue is asking for Avash to reference Gecko's
repo. This is an anti pattern and bad for bundling. I'm going to close my
this and just say we will update if gecko does.

--Collin

**Comment by danlaine** [comment]
Sounds good to me :+1:
