### ISSUE TITLE
Installation fails to work as intended if "go.mod" file present

### ISSUE THREAD

**Issue by michaelbnewman** [ava-labs/avash#46]
INTRO:

After installing gecko 0.5.5, I was confused why the standard avash install directions were not working:
`$ go get github.com/ava-labs/avash`
`$ cd $GOPATH/src/github.com/ava-labs/avash`
`No such file or directory`
The initial sign that things to wrong is the "avash" folder is not present in the $GOPATH

SUMMARY:

I discovered the core issue is that avash cannot be installed in a directory that has a "go.mod" file present, such as the gecko installation directory. Install directions for avash should warn user to be either in a clean directory, or perhaps switch to `cd $GOPATH` since that should not have "go.mod" directly in it.

DETAILS:

Let's revisit my issue via docker. I create a "mike" user to mimic conditions on my regular bare metal system:

TEST 1: ITS GOING TO BE UGLY

docker run --name avashtest1 -it ubuntu:bionic bash
apt update
apt install -y curl git mercurial make binutils bison gcc build-essential golang
adduser mike
su - mike
bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
source /home/mike/.gvm/scripts/gvm
gvm install go1.13.12
gvm use go1.13.12 --default
echo System general setup done.
go get -d -v github.com/ava-labs/gecko/...
cd $GOPATH/src/github.com/ava-labs/gecko
pwd  # /home/mike/.gvm/pkgsets/go1.13.12/global/src/github.com/ava-labs/gecko
./scripts/build.sh
./build/ava --version  # avalanche/0.5.5
test -f go.mod && echo WARNING: go.mod file found. Avash will not install correctly. Please switch to another directory. || echo INFO: go.mod file not found. Avash ready for installation.
go get github.com/ava-labs/avash
**cd $GOPATH/src/github.com/ava-labs/avash  #  No such file or directory**

What happened? The presence of "go.mod" file caused it to be built and stored as a module!
$ find ~/ | grep /avash$
/home/mike/.gvm/pkgsets/go1.13.12/global/bin/avash
/home/mike/.gvm/pkgsets/go1.13.12/global/pkg/mod/cache/download/github.com/ava-labs/avash

TEST 2: THIS WORKS

docker run --name avashtest2 -it ubuntu:bionic bash
apt update
apt install -y curl git mercurial make binutils bison gcc build-essential golang
adduser mike
su - mike
bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
source /home/mike/.gvm/scripts/gvm
gvm install go1.13.12
gvm use go1.13.12 --default
echo System general setup done.
go get -d -v github.com/ava-labs/gecko/...
cd $GOPATH/src/github.com/ava-labs/gecko
pwd  # /home/mike/.gvm/pkgsets/go1.13.12/global/src/github.com/ava-labs/gecko
./scripts/build.sh
./build/ava --version  # avalanche/0.5.5
cd  $GOPATH  # Let's go a directory without "go.mod" file
test -f go.mod && echo WARNING: go.mod file found. Avash will not install correctly. Please switch to another directory. || echo INFO: go.mod file not found. Avash ready for installation.
go get github.com/ava-labs/avash
cd $GOPATH/src/github.com/ava-labs/avash
pwd  # /home/mike/.gvm/pkgsets/go1.13.12/global/src/github.com/ava-labs/avash
go build

$ find ~/ | grep /avash$
/home/mike/.gvm/pkgsets/go1.13.12/global/bin/avash
/home/mike/.gvm/pkgsets/go1.13.12/global/src/github.com/ava-labs/avash
/home/mike/.gvm/pkgsets/go1.13.12/global/src/github.com/ava-labs/avash/avash

$ file avash
avash: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, not stripped

**Comment by collincusce** [comment]
Hey I don't know how go modules work, what is the difference between Test 1 and Test 2? What needs to be fixed?

**Comment by michaelbnewman** [comment]
Modules take any requested library to be installed and isolates it to the active project. So if I install gecko and stay in the gecko install directory, moving on immediately to avash install messing it up because it thinks i'm trying to integrate it directly with gecko. Something as simply as putting a note in the install directions to start with a clean directory (essentially without a "go.mod" file in it) solves the issue.

**Comment by collincusce** [comment]
This sounds like Golang behavior and not avash behavor. Plus I don't think our instructions say to do what you did.

https://github.com/ava-labs/avash#quick-setup

**Comment by michaelbnewman** [comment]
Existing steps:
1. - Install and build an AVA client
2. - go get github.com/ava-labs/avash

There is no step 1.5 saying to leave the gecko AVA client install directory. I leave it your discretion if overkill to tell someone that. As being myself previously not familiar with golang modules, it was very confusing for me. Its here for historical records on github if someone else stumbles the say way I did.

**Comment by collincusce** [comment]
Our steps are:

1. Install and build an AVA client
2. go get github.com/ava-labs/avash
3. cd $GOPATH/src/github.com/ava-labs/avash
4. go build

They already do tell you to go to the avash directory before building.

I don't see the issue here?

**Comment by collincusce** [comment]
I think we document what you're asking for already. I'm closing this issue. If you have more details we can chat in Discord and I'll see where the confusion is, but our existing steps already put you in the avash directory.
